use smart_probe

CREATE TABLE `testagent` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '测试代理机ID，自动递增',
  `name` varchar(32) COMMENT '测试代理机的别名标识',
  `ip` varchar(40) COMMENT '接入公网的IP',
  `bandwidth` double,
  `city` varchar(32) COMMENT '地市（自动获取）',
  `city_man` varchar(32) COMMENT '地市',
  `county` varchar(32) COMMENT '区县',
  `useruid` varchar(64) COMMENT '用户唯一标识，由sysuuid加密后转换得到',
  `sysuuid` varchar(64) COMMENT '测试机硬件唯一标识',
  `location` varchar(64) COMMENT '测试机的归属地，如福州长乐区、福州市连江区，扩展此字段可针对不同归属地进行报表统计',
  `isp` varchar(64) COMMENT '测试机接入的归属运营商，如电信、移动，扩展此字段可针对不同归属运营商进行报表统计',
  `accesslayer` varchar(64) COMMENT '设备所属的接入网络所属层面,包含用户侧、接入侧、汇聚层、，四个字符串的枚举',
  `accesstype` varchar(64) COMMENT '接入方式类型，包含ADSL、EPON、GPON、FTTx+LAN、LAN、专线、CN2、汇聚层等字符串的枚举',
  `uplink` varchar(64) COMMENT '上联设备名称，如ADSL接入可填写已存在的汇聚层测试机的名称、也可填写不在此系统中的BRAS名称，可用于两个层面的用户感知指标对比、也可用于统计上一联设备如多个BRAS的用户感知指标对比',
  `testgroup` int(11) COMMENT '测试任务组编号',
  `testgroup_name` varchar(64) COMMENT '测试任务组名',
  `onlinestatus` varchar(32) COMMENT '在线状态',
  `online_time` datetime COMMENT '上线时间',
  `register_time` datetime COMMENT '注册时间',
  `model` varchar(32) COMMENT '硬件版本类型',
  `device` varchar(32) COMMENT '设备型号',
  `teststatus` varchar(32) COMMENT '任务状态',
  `version` varchar(16) COMMENT '软件版本类型',
  `run_interval` int(11) COMMENT '任务间隔',
  `contact` varchar(32) COMMENT '装机联系人',
  `address` varchar(128) COMMENT '装机地址',
  `brasname` varchar(64) COMMENT 'BRAS名称',
  `brasip` varchar(32) COMMENT 'BRAS_IP',
  `brasport` varchar(32) COMMENT 'BRAS端口',
  `oltname` varchar(32) COMMENT 'OLT名',
  `oltip` varchar(32) COMMENT 'OLT_IP',
  `oltport` varchar(32) COMMENT 'OLT端口',
  `phonenum` varchar(32) COMMENT '维护人电话',
  `dayreport` int(11) COMMENT '健康度',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='探针信息表';

CREATE TABLE `result_pingtest` (
  `id` int(19) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `guid` varchar(64) COMMENT '测试任务分组',
  `state` int(3) COMMENT '成功失败标记',
  `errorcode` varchar(128) COMMENT '失败原因',
  `destid` int(10) COMMENT '测试端口ID',
  `destname` varchar(255) COMMENT '测试目标',
  `destip` varchar(32) COMMENT '目标IP',
  `testtime` datetime COMMENT '测试时间',
  `testagent` varchar(64) COMMENT '测试机',
  `qoe` double(22,0) COMMENT 'qoe',
  `bandwidth` double(22,0) COMMENT '带宽',
  `rtt_avg` double(22,0) COMMENT '平均时延',
  `rtt_min` double(22,0) COMMENT '最小时延',
  `rtt_max` double(22,0) COMMENT '最大时延',
  `rtt_std` double(22,0) COMMENT '时延方差',
  `jitter` double(22,0) COMMENT '抖动',
  `loss` double(22,0) COMMENT '丢包',
  `testagentid` int(10) COMMENT '测试机id',
  PRIMARY KEY (`id`),
  FOREIGN KEY (`testagentid`) REFERENCES testagent(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='ping测试结果表';

CREATE TABLE `result_youkutest` (
  `id` int(19) NOT NULL AUTO_INCREMENT,
  `guid` varchar(64) COMMENT '测试任务分组',
  `state` int(3) COMMENT '成功失败标记',
  `errorcode` varchar(128) COMMENT '失败原因',
  `destid` int(10) COMMENT 'destid',
  `destname` varchar(255) COMMENT '测试目标',
  `testtime` datetime COMMENT '测试时间',
  `testagent` varchar(64) COMMENT '测试机',
  `qoe` double(22,0) COMMENT 'qoe',
  `bandwidth` double(22,0) COMMENT '带宽',
  `speed` double(22,0) COMMENT '下载速率',
  `pausecount` double(22,0) COMMENT '停顿次数',
  `pausetime` double(22,0) COMMENT '停顿时长',
  `buffersize` double(22,0) COMMENT '缓冲区大小',
  `buffertime` double(22,0) COMMENT '缓冲区占满时长',
  `speedsize` double(22,0) COMMENT '下载总流量',
  `testagentid` int(10) COMMENT 'testagentid',
  PRIMARY KEY (`id`),
  FOREIGN KEY (`testagentid`) REFERENCES testagent(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='视频测试结果表';

CREATE TABLE `result_httptest` (
  `id` int(19) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `guid` varchar(255) COMMENT '测试任务组',
  `state` int(3) COMMENT '成功失败标记',
  `errorcode` varchar(128) COMMENT '失败原因',
  `destid` int(10) COMMENT '任务ID',
  `destname` varchar(255) COMMENT '测试目标',
  `destip` varchar(32) COMMENT '目标IP',
  `testtime` datetime COMMENT '测试时间',
  `alldelay` double(22,0) COMMENT '总时延',
  `screendelay` double(22,0) COMMENT '首屏时延',
  `testagent` varchar(64) COMMENT '测试机',
  `qoe` double(22,0) COMMENT 'qoe',
  `bandwidth` double(22,0) COMMENT '带宽',
  `speed` double(22,0) COMMENT 'HTTP下载速率',
  `dnsdelay` double(22,0) COMMENT 'DNS时延',
  `connectdelay` double(22,0) COMMENT '连接时延',
  `responsedelay` double(22,0) COMMENT '响应时延',
  `downloaddelay` double(22,0) COMMENT '下载时延',
  `httpsize` double(22,0) COMMENT '下载字节',
  `httpstatus` int(10) COMMENT 'http状态码',
  `testagentid` int(10) COMMENT '探针ID',
  PRIMARY KEY (`id`),
  FOREIGN KEY (`testagentid`) REFERENCES testagent(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='网页测试结果表';

CREATE TABLE `result_gametest` (
  `id` int(10) NOT NULL AUTO_INCREMENT COMMENT'id',
  `guid` varchar(192) COMMENT'测试任务分组',
  `state` int(3) COMMENT'成功失败标记',
  `errorcode` varchar(384) COMMENT'失败原因',
  `destid` int(10) COMMENT'destid',
  `destname` varchar(765) COMMENT'测试目标',
  `destip` varchar(96) COMMENT'目标IP',
  `testtime` datetime COMMENT'测试时间',
  `testagent` varchar(192) COMMENT'探针名',
  `qoe` double(22,0) COMMENT'qoe',
  `bandwidth` double(22,0) COMMENT'带宽',
  `rtt_avg` double(22,0) COMMENT'平均时延',
  `rtt_min` double(22,0) COMMENT'最小时延',
  `rtt_max` double(22,0) COMMENT'最大时延',
  `rtt_std` double(22,0) COMMENT'时延方差',
  `tcpconnect` double(22,0) COMMENT'tcp连接时延',
  `jitter` double(22,0) COMMENT'抖动',
  `loss` double(22,0) COMMENT'丢包',
  `testagentid` int(10) COMMENT'testagentid',
  PRIMARY KEY (`id`),
  FOREIGN KEY (`testagentid`) REFERENCES testagent(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='游戏测试结果表';